name: Detect IB-Gateway Releases

on:
  push:

  workflow_dispatch:

defaults:
  run:
    shell: "bash -Eeuo pipefail -x {0}"

jobs:
  detect-release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        channel: ["stable", "latest"]
    steps:
      - name: Cache Versions
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ matrix.channel }}-versions
          key: ${{ runner.os }}-${{ matrix.channel }}-versions

      - name: Get Latest Version
        id: version
        run: |
          res=$(curl -s https://download2.interactivebrokers.com/installers/tws/${{ matrix.channel }}-standalone/version.json | sed 's/tws${{ matrix.channel }}_callback(//g;s/);//g')
          build_version=$(jq -r '.buildVersion' <<< "$res")
          #build_dateTime=$(jq -r '.buildDateTime' <<< "$res")
          echo "::set-output name=build_version::$build_version"
          #echo "::set-output name=build_dateTime::$build_dateTime"

      - name: Check if there is an update
        id: check-update
        run: |
          if [ ! -f ${{ matrix.channel }}-versions ] || [ ! grep -Fxq "${{ steps.version.outputs.build_version }}" ${{ matrix.channel }}-versions ]
          then
            echo "::set-output name=has_update::true"
          else
            echo "::set-output name=has_update::false"
          fi

      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          lfs: true

      - name: Download
        if: ${{ steps.check-update.outputs.has_update == 'true' }}
        run: |
          download_url='https://download2.interactivebrokers.com/installers/ibgateway/${{ matrix.channel }}-standalone/ibgateway-${{ matrix.channel }}-standalone-linux-x64.sh'
          dest='./ibgateway-releases/ibgateway-${{ steps.version.outputs.build_version }}-standalone-linux-x64.sh'
          curl -sSL "$download_url" --output "$dest"
          sha256sum "$dest" > "${dest}.sha256"

      - name: Commit
        if: ${{ steps.check-update.outputs.has_update == 'true' }}
        run: |
          cd ./ibgateway-releases

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "add new ib-gateway ${{ steps.version.outputs.build_version }} (${{ matrix.channel }}) release file"
          #git push

      - name: Create Issue
        if: ${{ steps.check-update.outputs.has_update == 'true' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue create \
            --repo ${{ github.action_repository }}
            --title "IB-Gateway ${{ steps.version.outputs.build_version }} (${{ matrix.channel }}) was released" \
            --body "**Build Version:** ${{ steps.version.outputs.build_version }}\n**Channel:** ${{ matrix.channel }}\n[ibgateway-releases](https://github.com/UnusualAlpha/ib-gateway-docker/tree/gh-pages/ibgateway-releases)"

      # - name: Update Versions File
      #   if: ${{ steps.check-update.outputs.has_update == 'true' }}
      #   run: echo "${{ steps.version.outputs.build_version }}" >> ${{ matrix.channel }}-versions
